version: "3"
services:
      app:
        build:
          dockerfile: Dockerfile
          context: .
        links:
          - mysql
        depends_on:
          - mysql 
        ports:
          - "5000:5000"
      mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_PORT=3306
          - MYSQL_DATABASE=sql_injections
          - MYSQL_ROOT_PASSWORD=supersecretpassword
          - MYSQL_PASSWORD=supersecretpassword
        ports:
          - "3306:3306"
        expose:
          - "3306"
        volumes:
          - "./database_scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
          - "./database_scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"